#!/bin/bash
#SBATCH --job-name=twoc3
#SBATCH --qos=long
#SBATCH --partition=h100
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=90G
#SBATCH --time=167:59:50
#SBATCH --output=output_%x_%j.log

set -euo pipefail
: "${D:?D must be exported by submit_all.sh}"
: "${J2:?J2 must be exported by submit_all.sh}"
: "${REPLICA:?REPLICA must be exported by submit_all.sh}"

module load nvhpc/24.7-mpi
module load cuda/12.5.1
source /home/pghosh/venvs/6adctmrg_Kuma/bin/activate

OUTDIR="./Results_J2_twoc3_${J2}/D_${D}/replica_${REPLICA}"
mkdir -p "${OUTDIR}"

python ./main_C3.py \
    --J2 "${J2}" \
    --ansatz twoc3 \
    --Ds "${D}" \
    --output-dir "${OUTDIR}"

echo "END OF JOB"
